Output preview.gif
Set Margin 0
Set Shell zsh
Set Theme "TokyoNightStorm"
Set FontFamily "Hack Nerd Font"
Set Width 1920
Set Height 1080
Type@500ms "neofetch"
Enter
Sleep 4.5s
Type@500ms "nvim ."
Enter
Sleep 3.5s
Type@1s "  .zshrc"
Sleep 2.5s
Enter
Sleep 4.5s
Type@1s " gg"
Sleep 2s
Type "1"
Sleep 4s
Type "2"
Sleep 4s
Type "3"
Sleep 4s
Type "4"
Sleep 4s
Type "5"
Sleep 4s
Type@1s "q"
Sleep 3s
Type@1s " qq"
Sleep 5s
